### ISSUE TITLE
Linux server issue

### ISSUE THREAD

**Issue by rwu2359** [SoliantMike/FM-Admin-API-Tool#2]
Because the Linux server doesn't support PHP etc the menu items cause a 500 error

Perhaps a checkbox to indicate if this is a Penguin server? Or infer it from the path locations?

**Comment by SoliantMike** [comment]
Agreed, and this is not only applicable to linux. As of FMS 19.2, php is no longer installed on Windows as well. I have updated so the GET is not performed by default when navigating to that panel, where you can manually use those, if they apply. Documentation for those API calls are still in place, so will leave those in this file as well.
