### ISSUE TITLE
SSL 500 error

### ISSUE THREAD

**Issue by rwu2359** [SoliantMike/FM-Admin-API-Tool#3]
Mike
Used the tool to generate request etc etc

Trying to upload the SSL to the server & got a 500 error. Worked correctly when I did it using the admin console with all same details...

**Comment by SoliantMike** [comment]
It seems to work under specific conditions. I believe the issue is with the Admin API itself rather than this file sending the request. Personally I would use the CLI or admin console to manage SSL for now.

**Comment by rwu2359** [comment]
Thanks... great file otherwise
