### ISSUE TITLE
Field set to wrong type

### ISSUE THREAD

**Issue by rwu2359** [SoliantMike/FM-Admin-API-Tool#5]
Mike
The size field in the files table is set to text, when it could be better as a number field, and the data returned from the admin api is a number.
It means the portal for files could be sorted by size..

Again, great file, use it all the time. Thanks

**Comment by SoliantMike** [comment]
This was somewhat intentional, in order to keep the file simple, but I will take a look.

**Comment by rwu2359** [comment]
It's not a deal breaker, I make a few of my own hacks to your file and happy to carry on doing that.
Like tooltip on file size formatted in SI units..
